sudo: required
services:
 - docker 

before_install:
 - docker build -t seif-10/docker-react -f Dockerfile.dev

script:
 - docker run -e CI=true seif-10/docker-react npm run test

after_success: 
 - npm run coverage